name: UpdateTemp

on:
  schedule:
    - cron: '*/5 * * * *' 
jobs:
  before_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo README contents
        run: |
          cat README.md
