name: UpdateTemp

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' 
jobs:
  before_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test30
        env:
          TEMP: 'TEMP'
        run: |
          sed -i "s/<!--START-->.*<!--END-->/ ${TEMP} /g" README.md
      - name: Commit changes
        run: |
          git config user.name "temp bot"
          git config user.email "tempbot@ozwk.net"
          git add README.md
          git commit -m "Add AAAAA to README"
          git push
