name: UpdateTemp

on:
  schedule:
    - cron: '*/5 * * * *' 
jobs:
  before_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test7
        run: |
          TEST=$(curl -s https://temp.ozwk.net)
          sed -i 's/<!--START-->.*<!--END-->/<!--START-->"$TEST"<!--END-->/g' README.md
      - name: Commit changes
        run: |
          git config user.name "temp bot"
          git config user.email "tempbot@ozwk.net"
          git add README.md
          git commit -m "Add AAAAA to README"
          git push
