name: UpdateTemp

on:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  update_readme:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get data from temp.ozwk.net
      run: |
        curl -s http://temp.ozwk.net > temp_data.txt
        echo $("test")
        echo $(cat temp_data.txt)
