name: UpdateTemp

on:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  update_readme:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get data from temp.ozwk.net
      run: |
        curl -s http://temp.ozwk.net > temp_data.txt

    - name: Update README.md
      run: |
        TEMP_DATA=$(cat temp_data.txt)
        sed -i '/<!--START-->/, /<!--END-->/c\<!--START-->\n'"$TEMP_DATA"'\n<!--END-->' README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update README with temp.ozwk.net data'
        git push
